###
POST http://localhost:8080/create-user HTTP/1.1
content-type: application/json

{
  "username": "hoge",
  "password": "password"
}

###
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "username": "hoge",
  "password": "password"
}

###
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "username": "hoge",
  "password": "invalid"
}