CREATE TABLE IF NOT EXISTS task
(
    id    BIGSERIAL PRIMARY KEY,
    title CHARACTER VARYING(255) NOT NULL,
    done  BOOLEAN                NOT NULL
);

CREATE TABLE IF NOT EXISTS article
(
    id    BIGSERIAL PRIMARY KEY,
    title CHARACTER VARYING(255) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
