CREATE TABLE IF NOT EXISTS task
(
    id    BIGSERIAL PRIMARY KEY,
    title CHARACTER VARYING(255) NOT NULL,
    done  BOOLEAN                NOT NULL
);

CREATE TABLE IF NOT EXISTS login_user
(
    id       BIGSERIAL PRIMARY KEY,
    username CHARACTER VARYING(255) UNIQUE NOT NULL,
    password CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS github_user
(
    id           BIGINT PRIMARY KEY,
    access_token CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS article
(
    id         BIGSERIAL PRIMARY KEY,
    title      CHARACTER VARYING(255) NOT NULL,
    body       TEXT  NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
